export const PROVIDERS = {
  SUPABASE_SERVICE: 'SUPABASE_SEVICE',
  ENV_CONFIG_SERVICE: 'ENV_CONFIG_SERVICE',
  TRANSPARENCY_PORTAL_REPOSITORY: 'TRANSPARENCY_PORTAL_REPOSITORY',
  TRANSPARENCY_TYPE_REPOSITORY: 'TRANSPARENCY_TYPE_REPOSITORY',
  ROLE_REPOSITORY: 'ROLE_REPOSITORY',
  USER_REPOSITORY: 'USER_REPOSITORY',
  HASH_SERVICE: 'HASH_SERVICE',
  JWT_SERVICE: 'JWT_SERVICE',
  LOGGED_USER_SERVICE: 'LOGGED_USER_SERVICE'
};
