export const PROVIDERS = {
  SUPABASE_SERVICE: 'SUPABASE_SEVICE',
  ENV_CONFIG_SERVICE: 'ENV_CONFIG_SERVICE',
  TRANSPARENCY_PORTAL_REPOSITORY: 'TRANSPARENCY_PORTAL_REPOSITORY',
  TRANSPARENCY_TYPE_REPOSITORY: 'TRANSPARENCY_TYPE_REPOSITORY'
};
